development:
  url_address: 'localhost'
  url_port: 4000
  send_order_endpoint: '/api/v1/order/new'
  token: ''
test:
  url_address: 'localhost'
  url_port: 4000
  send_order_endpoint: 'api/v1/order/new'
  token: ''
